from __future__ import annotations
from datetime import date
from typing import Protocol
import pandas as pd
class MarketDataSource(Protocol):
    def get_equity_bars(self, symbol: str, start: date, end: date, bar_size: str = "1 day") -> pd.DataFrame: ...
    def get_option_chain(self, underlying: str, asof: date) -> pd.DataFrame: ...
    def get_option_bars(self, contracts: pd.DataFrame, start: date, end: date, bar_size: str = "1 day") -> pd.DataFrame: ...
